server {
    listen 80;
    server_name localhost;

    # Sirve los archivos estáticos de React
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html; # Soluciona el error 404 de React Router
    }

    # Replica el proxy de Vite para producción
    location ~ ^/api/(.*)$ {
        set $upstream_endpoint https://qic534o8o0.execute-api.us-east-1.amazonaws.com/$1;
        proxy_pass $upstream_endpoint;
        proxy_ssl_server_name on;
    }
}