server {
    listen 80;
    server_name localhost;

    # Sirve los archivos estáticos de React
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html; # Soluciona el error 404 de React Router
    }

    # Replica el proxy de Vite para producción
    location /api/v1/ventas {
        proxy_pass http://ventas-service:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Enrutamiento interno hacia el Backend de Despachos
    location /api/v1/despachos {
        proxy_pass http://despachos-service:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}